In [1]:
%matplotlib inline
import random

import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

matplotlib.style.use('ggplot')
random.seed()

In [2]:
train = pd.read_csv('Features_Variant_1.csv', sep=',')
train.head()

,likes,Checkins,Returns,Category,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,fri_pub,sat_pub,sun_base,mon_base,tue_base,wed_base,thu_base,fri_base,sat_base,output
0,634995,0,463,1,0,806,11.291045,1.0,70.495138,0,...,0,0,0,0,0,0,0,0,1,0
1,634995,0,463,1,0,806,11.291045,1.0,70.495138,0,...,0,0,0,0,0,0,0,1,0,0
2,634995,0,463,1,0,806,11.291045,1.0,70.495138,0,...,1,0,0,0,0,0,0,0,1,0
3,634995,0,463,1,0,806,11.291045,1.0,70.495138,0,...,1,0,0,1,0,0,0,0,0,0
4,634995,0,463,1,0,806,11.291045,1.0,70.495138,0,...,0,0,0,0,0,1,0,0,0,0

In [3]:
# Нормировка и сохранение коэффициентов
norm_coeffs = {}
for column in train.columns[:-1]:
    mean = np.mean(train[column])
    std = np.std(train[column])
    norm_coeffs[column] = {'mean': mean, 'std': std}
    train[column] = (train[column] - mean) / std
train.head()

,likes,Checkins,Returns,Category,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,fri_pub,sat_pub,sun_base,mon_base,tue_base,wed_base,thu_base,fri_base,sat_base,output
0,-0.100037,-0.227075,-0.399678,-1.165633,-0.076435,0.730167,-0.511079,-0.495224,0.037159,-0.021827,...,-0.413734,-0.398309,-0.406216,-0.390827,-0.399501,-0.417774,-0.421477,-0.409962,2.429384,0
1,-0.100037,-0.227075,-0.399678,-1.165633,-0.076435,0.730167,-0.511079,-0.495224,0.037159,-0.021827,...,-0.413734,-0.398309,-0.406216,-0.390827,-0.399501,-0.417774,-0.421477,2.439248,-0.411627,0
2,-0.100037,-0.227075,-0.399678,-1.165633,-0.076435,0.730167,-0.511079,-0.495224,0.037159,-0.021827,...,2.417010,-0.398309,-0.406216,-0.390827,-0.399501,-0.417774,-0.421477,-0.409962,2.429384,0
3,-0.100037,-0.227075,-0.399678,-1.165633,-0.076435,0.730167,-0.511079,-0.495224,0.037159,-0.021827,...,2.417010,-0.398309,-0.406216,2.558674,-0.399501,-0.417774,-0.421477,-0.409962,-0.411627,0
4,-0.100037,-0.227075,-0.399678,-1.165633,-0.076435,0.730167,-0.511079,-0.495224,0.037159,-0.021827,...,-0.413734,-0.398309,-0.406216,-0.390827,-0.399501,2.393637,-0.421477,-0.409962,-0.411627,0

In [4]:
tests = [pd.read_csv(f'Test_Case_{i}.csv', sep=',', header=None, names=train.columns) for i in range(1, 11)]
test = pd.concat(tests, ignore_index=True)
for column in train.columns[:-1]:
    test[column] = (test[column] - norm_coeffs[column]['mean']) / norm_coeffs[column]['std']
print(test.shape)
test.head()

(1000, 53)

,likes,Checkins,Returns,Category,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,fri_pub,sat_pub,sun_base,mon_base,tue_base,wed_base,thu_base,fri_base,sat_base,output
0,-0.188615,2.171418,-0.403771,-1.215758,36.930406,-0.737149,-0.221096,1.389605,-0.827098,27.327688,...,-0.413734,-0.398309,-0.406216,-0.390827,-0.399501,-0.417774,2.372608,-0.409962,-0.411627,35
1,-0.193616,0.063219,-0.403816,-1.065384,3.537515,-0.846847,-0.468414,-0.175190,-0.790319,7.437132,...,2.417010,-0.398309,-0.406216,-0.390827,-0.399501,-0.417774,-0.421477,-0.409962,2.429384,2
2,-0.193603,1.462097,-0.403221,-1.215758,-0.076435,-0.892578,-0.640962,-0.509518,-0.827098,-0.021827,...,-0.413734,-0.398309,-0.406216,-0.390827,-0.399501,-0.417774,-0.421477,-0.409962,2.429384,0
3,-0.193616,-0.061678,-0.403698,-1.215758,0.983657,-0.884525,-0.629458,-0.415182,-0.827098,2.166134,...,-0.413734,2.510616,2.461742,-0.390827,-0.399501,-0.417774,-0.421477,-0.409962,-0.411627,0
4,-0.193616,29.591067,-0.403771,-1.215758,46.085744,-0.759750,-0.364885,1.305261,-0.827098,78.247513,...,-0.413734,2.510616,2.461742,-0.390827,-0.399501,-0.417774,-0.421477,-0.409962,-0.411627,0

In [5]:
# Разбиение на X и y
# bias will be first
X_train = train.drop(columns=['output'])
tmp = X_train.columns.tolist()
X_train['bias'] = 1
X_train = X_train[['bias'] + tmp]
y_train = train['output']

X_test = test.drop(columns=['output'])
tmp = X_test.columns.tolist()
X_test['bias'] = 1
X_test = X_test[['bias'] + tmp]
y_test = test['output']

X_np = X_train.to_numpy()
y_np = y_train.to_numpy()

X_test_np = X_test.to_numpy()
y_test_np = y_test.to_numpy()

X_train.head()

,bias,likes,Checkins,Returns,Category,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,...,thu_pub,fri_pub,sat_pub,sun_base,mon_base,tue_base,wed_base,thu_base,fri_base,sat_base
0,1,-0.100037,-0.227075,-0.399678,-1.165633,-0.076435,0.730167,-0.511079,-0.495224,0.037159,...,-0.410206,-0.413734,-0.398309,-0.406216,-0.390827,-0.399501,-0.417774,-0.421477,-0.409962,2.429384
1,1,-0.100037,-0.227075,-0.399678,-1.165633,-0.076435,0.730167,-0.511079,-0.495224,0.037159,...,2.437799,-0.413734,-0.398309,-0.406216,-0.390827,-0.399501,-0.417774,-0.421477,2.439248,-0.411627
2,1,-0.100037,-0.227075,-0.399678,-1.165633,-0.076435,0.730167,-0.511079,-0.495224,0.037159,...,-0.410206,2.417010,-0.398309,-0.406216,-0.390827,-0.399501,-0.417774,-0.421477,-0.409962,2.429384
3,1,-0.100037,-0.227075,-0.399678,-1.165633,-0.076435,0.730167,-0.511079,-0.495224,0.037159,...,-0.410206,2.417010,-0.398309,-0.406216,2.558674,-0.399501,-0.417774,-0.421477,-0.409962,-0.411627
4,1,-0.100037,-0.227075,-0.399678,-1.165633,-0.076435,0.730167,-0.511079,-0.495224,0.037159,...,-0.410206,-0.413734,-0.398309,-0.406216,-0.390827,-0.399501,2.393637,-0.421477,-0.409962,-0.411627

In [6]:
def shuffled(X: np.ndarray, y: np.ndarray):
    zipped = np.hstack((X, y.reshape(-1, 1)))
    np.random.shuffle(zipped)
    shuffled_X, shuffled_y = np.hsplit(zipped, np.array([-1]))
    return shuffled_X, shuffled_y.reshape(-1)


def mae(fact: np.ndarray, pred: np.ndarray):
    return np.mean((fact - pred) ** 2)


def mae_(fact: np.ndarray, pred: np.ndarray):
    return mae(fact, pred) / 2


def rmse(fact: np.ndarray, pred: np.ndarray):
    return np.sqrt(np.mean((fact - pred) ** 2))


def r2(fact: np.ndarray, pred: np.ndarray):
    return 1 - mae(fact, pred) / mae(fact, np.mean(fact))


def loss_and_grad(X: np.ndarray, y: np.ndarray, thetas: np.ndarray,
                  reg: float):
    n, m = X.shape
    preds = X @ thetas
    X_tr = X.transpose()
    
    main_grad = 1 / n * X_tr @ (preds - y)
    reg_grad = reg / (m * n) * thetas
    # По bias не пускают регуляризацию
    reg_grad[0] = 0
    result_grad = main_grad + reg_grad
    return mae_(y, preds), result_grad


def grad_descent(X: np.ndarray, y: np.ndarray, lr: float, reg: float,
                 stopping_thresh: float, max_iters: int = 100):
    n, m = X.shape
    assert y.shape == (n,)
    thetas = np.random.randn(m) * np.sqrt(1 / m)
    last_loss = -100
    for _ in range(max_iters):
        loss, grad = loss_and_grad(X, y, thetas, reg)
        if np.abs(loss - last_loss) < stopping_thresh:
            break
        thetas = thetas - lr * grad
        last_loss = loss

    return thetas


def get_kfold_errors(X: np.ndarray, y: np.ndarray, lr: float, reg: float,
                     stopping_thresh: float, n_folds: int = 5):
    assert len(y.shape) == 1, X.shape[0] == y.shape[0]
    folds_X = np.array_split(X, n_folds)
    folds_y = np.array_split(y, n_folds)

    val_errors = []
    for i in range(n_folds):
        current_train_X = np.vstack([folds_X[j]
                                     for j in range(n_folds) if j != i])
        current_train_y = np.hstack([folds_y[j]
                                     for j in range(n_folds) if j != i])
        current_val_X = folds_X[i]
        current_val_y = folds_y[i]
        thetas = grad_descent(current_train_X, current_train_y, lr, reg,
                              stopping_thresh)
        current_error = rmse(current_val_y, current_val_X @ thetas)
        current_r2 = r2(current_val_y, current_val_X @ thetas)
        val_errors.append((current_error, current_r2))

    return val_errors

In [7]:
tested_params = []

## Тренировка и валидация с руками выставленными параметрами

In [8]:
hyperparams = {
    'lr': 0.1,
    'reg': 0.1,
    'stopping_thresh': 1
}

X_np, y_np = shuffled(X_np, y_np)
errors = get_kfold_errors(X_np, y_np, **hyperparams, n_folds=5)
print('Fold errors (RMSE, R2):')
for rmse_err, r2_err in errors:
    print(f'({rmse_err:.3f}, {r2_err:.3f})  ', end='')
print(f'\nMean: ({np.mean([rmse_err for rmse_err, _ in errors]):.3f}, ', end='')
print(f'{np.mean([r2_err for _, r2_err in errors]):.3f})\n')

thetas = grad_descent(X_np, y_np, **hyperparams)
train_pred = X_np @ thetas
test_pred = X_test_np @ thetas
print(f'\033[4m      |  RMSE  |  R^2  \033[0m')
print(f'\033[4mTrain | {rmse(y_np, train_pred):6.2f} | {r2(y_np, train_pred):5.3f} \033[0m')
print(f'Test  | {rmse(y_test_np, test_pred):6.2f} | {r2(y_test_np, test_pred):5.3f} ')

Fold errors (RMSE, R2):
(24.414, 0.400)  (33.866, 0.181)  (34.324, 0.319)  (23.580, 0.320)  (30.249, 0.326)
Mean: (29.286, 0.309)

      |  RMSE  |  R^2
Train |  29.51 | 0.309
Test  | 193.06 | -2.400

In [9]:
def get_random_hyperparams():
    hyperparams = {}
    min_lr = 0.001
    max_lr = 0.1
    hyperparams['lr'] = random.uniform(min_lr ** 0.5, max_lr ** 0.5) ** 2
    min_reg = 0.001
    max_reg = 1
    hyperparams['reg'] = random.uniform(min_reg ** 0.5, max_reg ** 0.5) ** 2
    min_stopping_thresh = 0.1
    max_stopping_thresh = 100
    hyperparams['stopping_thresh'] = random.uniform(
        min_stopping_thresh ** 0.5, max_stopping_thresh ** 0.5) ** 2
    
    return hyperparams

In [10]:
for i in range(100):
    print(i, end=' ')
    hyperparams = get_random_hyperparams()
    errors = get_kfold_errors(X_np, y_np, **hyperparams, n_folds=5)
    error = np.mean([rmse_err for rmse_err, _ in errors])
    tested_params.append((hyperparams, error))

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99

In [11]:
best_params = sorted(tested_params, key=lambda x: x[1])
best_params[:5]

[({'lr': 0.05806384571977147,
   'reg': 0.015732500772702416,
   'stopping_thresh': 0.32009621361643914},
  29.257281727893492),
 ({'lr': 0.05580175487635224,
   'reg': 0.6880194403216658,
   'stopping_thresh': 0.36719286136153917},
  29.26721400233314),
 ({'lr': 0.013667106234023963,
   'reg': 0.33012569940164893,
   'stopping_thresh': 0.10678884693729729},
  29.301371912475094),
 ({'lr': 0.047062811578817226,
   'reg': 0.01598332940933527,
   'stopping_thresh': 0.7578218758685105},
  29.37335009403909),
 ({'lr': 0.053967524846500595,
   'reg': 0.8565427236803574,
   'stopping_thresh': 1.1883416844318082},
  29.415509983323812)]

## Тренировка и валидация с параметрами, найденными случайным поиском

In [12]:
hyperparams = best_params[0][0]
thetas = grad_descent(X_np, y_np, **hyperparams)
train_pred = X_np @ thetas
test_pred = X_test_np @ thetas
print(f'\033[4m      |  RMSE  |  R^2  \033[0m')
print(f'\033[4mTrain | {rmse(y_np, train_pred):6.2f} | {r2(y_np, train_pred):5.3f} \033[0m')
print(f'Test  | {rmse(y_test_np, test_pred):6.2f} | {r2(y_test_np, test_pred):5.3f} ')

      |  RMSE  |  R^2
Train |  29.47 | 0.311
Test  | 201.70 | -2.711

## Картина не сильно поменялась...

In [13]:
from scipy import stats


def regression_coef(preds, thetas, X, y):
    coef = pd.DataFrame(list(zip(X.columns.tolist(), thetas.tolist())),
                        columns=['predictor', 'coef'])
    X1 = X.to_numpy()
    b = thetas
    MSE = np.sum((preds - y) ** 2, axis=0) / float(X.shape[0] - X.shape[1])
    var_b = MSE * (np.linalg.pinv(np.dot(X1.T, X1)).diagonal())
    sd_b = np.sqrt(var_b)
    t = b / sd_b
    coef['pvalue'] = [2 * (1 - stats.t.cdf(np.abs(i), (len(X1) - 1))) for i in t]
    return coef

In [14]:
# Да, можно было просто посмотреть на модуль самих коэффициентов, но мы не ищем простых путей
pvalue_table = regression_coef(train_pred, thetas, X_train, y_np)
pvalue_table

      predictor      coef        pvalue
0          bias  5.850483  0.000000e+00
1         likes -0.095956  6.254939e-01
2      Checkins -0.650336  3.683317e-05
3       Returns -0.539113  3.421906e-02
4      Category  0.002498  9.871477e-01
5    Unnamed: 4 -0.080011  9.750461e-01
6    Unnamed: 5  0.021357  9.945304e-01
7    Unnamed: 6  0.443277  9.671637e-01
8    Unnamed: 7  0.522396  8.998324e-01
9    Unnamed: 8  0.511992  9.401543e-01
10   Unnamed: 9 -0.269713  5.239560e-01
11  Unnamed: 10 -0.516655  8.170618e-01
12  Unnamed: 11  0.872816  4.914358e-01
13  Unnamed: 12  1.251644  8.698276e-02
14  Unnamed: 13  0.426668  8.455151e-01
15  Unnamed: 14 -0.375833  9.964349e-02
16  Unnamed: 15  0.190701  8.859570e-01
17  Unnamed: 16  0.860283  5.401066e-01
18  Unnamed: 17  1.355151  1.188998e-02
19  Unnamed: 18  0.242876  8.931693e-01
20  Unnamed: 19  0.012275  9.961410e-01
21  Unnamed: 20 -0.068810  9.823664e-01
22  Unnamed: 21  0.255487  9.803326e-01
23  Unnamed: 22  0.499983  8.988394e-01
24  Unnamed: 23  0.374601  9.557087e-01
25  Unnamed: 24  0.351490  7.400261e-01
26  Unnamed: 25 -0.252424  9.006529e-01
27  Unnamed: 26  0.353373  5.332620e-01
28  Unnamed: 27 -0.250289  5.308515e-01
29  Unnamed: 28  0.373812  8.342219e-01
30     commBase  1.574112  4.880187e-01
31       comm24  7.195272  0.000000e+00
32       comm48 -0.527338  2.734426e-02
33     comm24_1  1.945617  4.107135e-01
34   diff_24,48  6.191525  0.000000e+00
35     baseTime -4.377960  0.000000e+00
36       length  0.035745  8.071161e-01
37       shares  1.806563  0.000000e+00
38          hrs  0.766627  5.317243e-07
39      sun_pub -0.148910  2.954163e-01
40      mon_pub -0.225907  1.117698e-01
41      tue_pub -0.218047  1.229616e-01
42      wed_pub  0.071406  6.143519e-01
43      thu_pub -0.100169  4.791759e-01
44      fri_pub  0.041385  7.718775e-01
45      sat_pub -0.156513  2.740483e-01
46     sun_base -0.191413  1.813326e-01
47     mon_base  0.016412  9.087146e-01
48     tue_base -0.114938  4.205580e-01
49     wed_base  0.243147  8.776306e-02
50     thu_base -0.027851  8.434324e-01
51     fri_base  0.087463  5.348267e-01
52     sat_base -0.101679  4.718698e-01

### Возьмём только значимые фичи

In [15]:
good_features = pvalue_table[pvalue_table['pvalue'] < 0.05]['predictor']
good_features

0            bias
2        Checkins
3         Returns
18    Unnamed: 17
31         comm24
32         comm48
34     diff_24,48
35       baseTime
37         shares
38            hrs
Name: predictor, dtype: object

In [16]:
X_train_good = X_train[good_features.to_list()].to_numpy()
y_train_good = y_train.to_numpy()

hyperparams = best_params[0][0]
thetas = grad_descent(X_train_good, y_train_good, **hyperparams)
train_pred = X_train_good @ thetas
X_test_np = X_test[good_features.to_list()]
test_pred = X_test_np @ thetas
print(f'\033[4m      |  RMSE  |  R^2  \033[0m')
print(f'\033[4mTrain | {rmse(y_train_good, train_pred):6.2f} | {r2(y_train_good, train_pred):5.3f} \033[0m')
print(f'Test  | {rmse(y_test_np, test_pred):6.2f} | {r2(y_test_np, test_pred):5.3f} ')

      |  RMSE  |  R^2
Train |  29.52 | 0.308
Test  | 126.86 | -0.468

## $R^2$ на тесте значительно улучшилось